name: 'Build collection'

on:
  push:
    branches:
      - '**'
    paths:
      - '.github/workflows/**'
      - 'src/**'
      - '*.sln'
      - '*.props'
      - '*.targets'
      - '*.yml'
      - '*.yaml'
  pull_request:
    branches:
      - '**'
    paths:
      - '.github/workflows/**'
      - 'src/**'
      - '*.sln'
      - '*.props'
      - '*.targets'
      - '*.yml'
      - '*.yaml'

jobs:
  build-collection:
    name: 'Build collection'

    strategy:
      matrix:
        system:
          - windows-2022
        framework:
          - net6.0
          - net7.0
          - net8.0
          - net6.0-windows
          - net7.0-windows
          - net8.0-windows
        config:
          - Debug
          - Release

    runs-on: ${{ matrix.system }}

    env:
      Solution: HelpersCollection.sln

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Restore dependencies
        run: |
          dotnet restore $env:Solution

      - name: Build solution
        run: |
          dotnet build $env:Solution --framework ${{ matrix.framework }} --configuration ${{ matrix.config }} --no-restore

      - name: Run tests
        run:
          dotnet test $env:Solution --framework ${{ matrix.framework }} --configuration ${{ matrix.config }} --no-build --no-restore --verbosity normal

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: bin-(${{ matrix.config }})-(${{ github.sha }})
          path: bin/${{ matrix.config }}/
