name: 'Build collection'

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    name: 'Build'

    strategy:
      matrix:
        system:
          - windows-2022
        config:
          - Debug
          - Release

    runs-on: ${{ matrix.system }}

    env:
      Solution: HelpersCollection.sln

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Restore dependencies
        run: |
          dotnet restore $env:Solution

      - name: Build solution
        run: |
          dotnet build $env:Solution -p:Configuration=${{ matrix.config }} --no-restore

      - name: Run tests
        run:
          dotnet test $env:Solution -p:Configuration=${{ matrix.config }} --no-build --no-restore --verbosity normal

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: bin-(${{ matrix.config }})-(${{ github.sha }})
          path: bin/${{ matrix.config }}/
